services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_bd
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "123Elkt!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      
  sqlserver-init:
    build:
      context: ./database
    depends_on:
      - sqlserver
    environment:
      MSSQL_SA_PASSWORD: "123Elkt!"
    restart: "no"

volumes:
  sqlserver_data:


  
